### ISSUE TITLE
How to get Token and Download Id??

### ISSUE THREAD

**Issue by bhumikash-tech** [SIARAY/DownloadManagerPlus#18]
Hey I read the documentation of DownloadManagerPlus Library , I didn't understand the way of how to get token. As you mentionedthat to get token  - Downloader.getToken(context, downloadId); But how can I get downloadId. Is that meansI need to use Android Download Manager + your libraray to complete my project?????

Please clear this out .

**Comment by SIARAY** [comment]
> 

The token is actually the download manager plus ID you use to start each download. Please explain where you need to get the token? The method you wrote will be used if you have the ID of the Android Download Manager and you want to use it to get the Download Manager Plus token, which is usually not needed. With this library, you do not need to use Android Download Manager, because this library itself has used Android Download Manager optimally.

**Comment by SIARAY** [comment]
> Hey I read the documentation of DownloadManagerPlus Library , I didn't understand the way of how to get token. As you mentionedthat to get token - Downloader.getToken(context, downloadId); But how can I get downloadId. Is that meansI need to use Android Download Manager + your libraray to complete my project?????
> 
> Please clear this out .

The token is actually the download manager plus ID you use to start each download. Please explain where you need to get the token? The method you wrote will be used if you have the ID of the Android Download Manager and you want to use it to get the Download Manager Plus token, which is usually not needed. With this library, you do not need to use Android Download Manager, because this library itself has used Android Download Manager optimally.
